spring.application.name=jwtsecurity
server.port=8080
spring.datasource.url= jdbc:mysql://localhost:3306/jwtdb
spring.datasource.username=root
spring.datasource.password=root
#spring.jpa.database-plaltform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#logging.level.org.springframework.security=DEBUG